Revert Python interpreter discovery back to src/manage.py parsing

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -1,17 +1,20 @@
 #!/usr/bin/env bash
 
+MANAGE_SCRIPT=${MANAGE_SCRIPT:-src/manage.py}
+VENV_PATH=${VENV_PATH:-var/venv}
+
 if [ -z "$*" ]; then
 	cat >&2 <<END
 Commands:
 
-install               - install packages from requirements.txt (creates virtualenv on first invocation)
+install               - install packages from requirements.txt (creates virtualenv at ${VENV_PATH} on first invocation)
 virtualenv            - open shell inside virtualenv
 virtualenv <command>  - run <command> inside virtualenv (e.g. $0 virtualenv pip install foo)
 
-Anything else is passed to Django manage.py, e.g.:
+Anything else is passed to ${MANAGE_SCRIPT}, e.g.:
 
-migrate               - apply Django migrations
-runserver 8888        - run development server
+runserver             - run development server
+migrate               - apply migrations
 END
 	exit 1
 fi
@@ -22,12 +25,9 @@ die() { >&2 echo -e $@; exit 1; }
 
 cd $(dirname $(cd ${0%/*} && echo $PWD/${0##*/}))  # cd to own directory
 
-VENV_PATH=${VENV_PATH:-var/venv}
 if [ ! -f "$VENV_PATH/bin/activate" ]; then
-	PYTHON_VARIANTS=$(cat requirements.txt |grep '^# python: '| sed -re 's/.*://')
-	[ -n "$PYTHON_VARIANTS" ] || die "Add python variants to requirements.txt like this:\n# python: python3.5 python3.4"
-	for v in $PYTHON_VARIANTS; do python=$(which "$v"; true); if [ -n "$python" ]; then break; fi; done
-	[ -n "$python" ] || die "Could not find any of $PYTHON_VARIANTS"
+	python=$($(cat "$MANAGE_SCRIPT" | head -n 1 | tail -c +3) -c 'import sys; print(sys.executable)')
+	[ -x "$python" ] || die "Could not discover Python interpreter from $MANAGE_SCRIPT shebang"
 	virtualenv --python="$python" "$VENV_PATH" || die "Failed to initialize virtualenv at $VENV_PATH"
 fi
 
@@ -46,7 +46,6 @@ virtualenv)
 	fi
 	;;
 *)
-	DJANGO_SCRIPT=${DJANGO_SCRIPT:-src/manage.py}
-	python "$DJANGO_SCRIPT" "$@"
+	"$MANAGE_SCRIPT" "$@"
 	;;
 esac
